# Generated by Django 4.0.7 on 2022-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='endsOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='startsOn',
            field=models.DateTimeField(),
        ),
    ]
